# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import population_server_pb2 as population__server__pb2


class PopulationServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/PopulationServer/Ping',
        request_serializer=population__server__pb2.WorkerPing.SerializeToString,
        response_deserializer=population__server__pb2.Confirmation.FromString,
        )
    self.GetManagerStats = channel.unary_unary(
        '/PopulationServer/GetManagerStats',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=population__server__pb2.ManagerStats.FromString,
        )
    self.GetLatestPayoffTableKey = channel.unary_unary(
        '/PopulationServer/GetLatestPayoffTableKey',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=population__server__pb2.PayoffTableKey.FromString,
        )
    self.SubmitNewPolicyForPopulation = channel.unary_unary(
        '/PopulationServer/SubmitNewPolicyForPopulation',
        request_serializer=population__server__pb2.PolicyInfo.SerializeToString,
        response_deserializer=population__server__pb2.Confirmation.FromString,
        )
    self.RequestEvalMatchup = channel.unary_unary(
        '/PopulationServer/RequestEvalMatchup',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=population__server__pb2.EvalMatchupOrder.FromString,
        )
    self.SubmitEvalMatchupResult = channel.unary_unary(
        '/PopulationServer/SubmitEvalMatchupResult',
        request_serializer=population__server__pb2.EvalMatchupResult.SerializeToString,
        response_deserializer=population__server__pb2.Confirmation.FromString,
        )
    self.RequestEvalResult = channel.unary_unary(
        '/PopulationServer/RequestEvalResult',
        request_serializer=population__server__pb2.EvalResultRequest.SerializeToString,
        response_deserializer=population__server__pb2.EvalMatchupResult.FromString,
        )


class PopulationServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetManagerStats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLatestPayoffTableKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitNewPolicyForPopulation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestEvalMatchup(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitEvalMatchupResult(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestEvalResult(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PopulationServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=population__server__pb2.WorkerPing.FromString,
          response_serializer=population__server__pb2.Confirmation.SerializeToString,
      ),
      'GetManagerStats': grpc.unary_unary_rpc_method_handler(
          servicer.GetManagerStats,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=population__server__pb2.ManagerStats.SerializeToString,
      ),
      'GetLatestPayoffTableKey': grpc.unary_unary_rpc_method_handler(
          servicer.GetLatestPayoffTableKey,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=population__server__pb2.PayoffTableKey.SerializeToString,
      ),
      'SubmitNewPolicyForPopulation': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitNewPolicyForPopulation,
          request_deserializer=population__server__pb2.PolicyInfo.FromString,
          response_serializer=population__server__pb2.Confirmation.SerializeToString,
      ),
      'RequestEvalMatchup': grpc.unary_unary_rpc_method_handler(
          servicer.RequestEvalMatchup,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=population__server__pb2.EvalMatchupOrder.SerializeToString,
      ),
      'SubmitEvalMatchupResult': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitEvalMatchupResult,
          request_deserializer=population__server__pb2.EvalMatchupResult.FromString,
          response_serializer=population__server__pb2.Confirmation.SerializeToString,
      ),
      'RequestEvalResult': grpc.unary_unary_rpc_method_handler(
          servicer.RequestEvalResult,
          request_deserializer=population__server__pb2.EvalResultRequest.FromString,
          response_serializer=population__server__pb2.EvalMatchupResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PopulationServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
