# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: population_server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='population_server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x17population_server.proto\x1a\x1bgoogle/protobuf/empty.proto\"4\n\nWorkerPing\x12\x13\n\x0bworker_type\x18\x01 \x01(\t\x12\x11\n\tworker_id\x18\x02 \x01(\t\"<\n\x0ePayoffTableKey\x12\x1d\n\x15payoff_table_is_empty\x18\x01 \x01(\x08\x12\x0b\n\x03key\x18\x02 \x01(\t\"q\n\nPolicyInfo\x12\x12\n\npolicy_key\x18\x01 \x01(\t\x12\x1f\n\x17policy_model_config_key\x18\x02 \x01(\t\x12\x19\n\x11policy_class_name\x18\x03 \x01(\t\x12\x13\n\x0bpolicy_tags\x18\x04 \x03(\t\"5\n\x0c\x43onfirmation\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x8e\x01\n\x10\x45valMatchupOrder\x12\x1a\n\x12no_matchups_needed\x18\x01 \x01(\x08\x12\x1e\n\tas_policy\x18\x02 \x01(\x0b\x32\x0b.PolicyInfo\x12#\n\x0e\x61gainst_policy\x18\x03 \x01(\x0b\x32\x0b.PolicyInfo\x12\x19\n\x11num_games_to_play\x18\x04 \x01(\x05\"l\n\x11\x45valMatchupResult\x12\x15\n\ras_policy_key\x18\x01 \x01(\t\x12\x1a\n\x12\x61gainst_policy_key\x18\x02 \x01(\t\x12\x0e\n\x06payoff\x18\x03 \x01(\x02\x12\x14\n\x0cgames_played\x18\x04 \x01(\x05\"*\n\x0cManagerStats\x12\x1a\n\x12manager_stats_json\x18\x01 \x01(\t\"[\n\x11\x45valResultRequest\x12\"\n\x07matchup\x18\x01 \x01(\x0b\x32\x11.EvalMatchupOrder\x12\"\n\x1aperform_eval_if_not_cached\x18\x02 \x01(\x08\x32\xba\x03\n\x10PopulationServer\x12$\n\x04Ping\x12\x0b.WorkerPing\x1a\r.Confirmation\"\x00\x12:\n\x0fGetManagerStats\x12\x16.google.protobuf.Empty\x1a\r.ManagerStats\"\x00\x12\x44\n\x17GetLatestPayoffTableKey\x12\x16.google.protobuf.Empty\x1a\x0f.PayoffTableKey\"\x00\x12<\n\x1cSubmitNewPolicyForPopulation\x12\x0b.PolicyInfo\x1a\r.Confirmation\"\x00\x12\x41\n\x12RequestEvalMatchup\x12\x16.google.protobuf.Empty\x1a\x11.EvalMatchupOrder\"\x00\x12>\n\x17SubmitEvalMatchupResult\x12\x12.EvalMatchupResult\x1a\r.Confirmation\"\x00\x12=\n\x11RequestEvalResult\x12\x12.EvalResultRequest\x1a\x12.EvalMatchupResult\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_WORKERPING = _descriptor.Descriptor(
  name='WorkerPing',
  full_name='WorkerPing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_type', full_name='WorkerPing.worker_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='WorkerPing.worker_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=108,
)


_PAYOFFTABLEKEY = _descriptor.Descriptor(
  name='PayoffTableKey',
  full_name='PayoffTableKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payoff_table_is_empty', full_name='PayoffTableKey.payoff_table_is_empty', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='PayoffTableKey.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=170,
)


_POLICYINFO = _descriptor.Descriptor(
  name='PolicyInfo',
  full_name='PolicyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='policy_key', full_name='PolicyInfo.policy_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='policy_model_config_key', full_name='PolicyInfo.policy_model_config_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='policy_class_name', full_name='PolicyInfo.policy_class_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='policy_tags', full_name='PolicyInfo.policy_tags', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=285,
)


_CONFIRMATION = _descriptor.Descriptor(
  name='Confirmation',
  full_name='Confirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confirmation', full_name='Confirmation.confirmation', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='Confirmation.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=340,
)


_EVALMATCHUPORDER = _descriptor.Descriptor(
  name='EvalMatchupOrder',
  full_name='EvalMatchupOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='no_matchups_needed', full_name='EvalMatchupOrder.no_matchups_needed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='as_policy', full_name='EvalMatchupOrder.as_policy', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='against_policy', full_name='EvalMatchupOrder.against_policy', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_games_to_play', full_name='EvalMatchupOrder.num_games_to_play', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=485,
)


_EVALMATCHUPRESULT = _descriptor.Descriptor(
  name='EvalMatchupResult',
  full_name='EvalMatchupResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='as_policy_key', full_name='EvalMatchupResult.as_policy_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='against_policy_key', full_name='EvalMatchupResult.against_policy_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payoff', full_name='EvalMatchupResult.payoff', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='games_played', full_name='EvalMatchupResult.games_played', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=595,
)


_MANAGERSTATS = _descriptor.Descriptor(
  name='ManagerStats',
  full_name='ManagerStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='manager_stats_json', full_name='ManagerStats.manager_stats_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=639,
)


_EVALRESULTREQUEST = _descriptor.Descriptor(
  name='EvalResultRequest',
  full_name='EvalResultRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matchup', full_name='EvalResultRequest.matchup', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='perform_eval_if_not_cached', full_name='EvalResultRequest.perform_eval_if_not_cached', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=641,
  serialized_end=732,
)

_EVALMATCHUPORDER.fields_by_name['as_policy'].message_type = _POLICYINFO
_EVALMATCHUPORDER.fields_by_name['against_policy'].message_type = _POLICYINFO
_EVALRESULTREQUEST.fields_by_name['matchup'].message_type = _EVALMATCHUPORDER
DESCRIPTOR.message_types_by_name['WorkerPing'] = _WORKERPING
DESCRIPTOR.message_types_by_name['PayoffTableKey'] = _PAYOFFTABLEKEY
DESCRIPTOR.message_types_by_name['PolicyInfo'] = _POLICYINFO
DESCRIPTOR.message_types_by_name['Confirmation'] = _CONFIRMATION
DESCRIPTOR.message_types_by_name['EvalMatchupOrder'] = _EVALMATCHUPORDER
DESCRIPTOR.message_types_by_name['EvalMatchupResult'] = _EVALMATCHUPRESULT
DESCRIPTOR.message_types_by_name['ManagerStats'] = _MANAGERSTATS
DESCRIPTOR.message_types_by_name['EvalResultRequest'] = _EVALRESULTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkerPing = _reflection.GeneratedProtocolMessageType('WorkerPing', (_message.Message,), {
  'DESCRIPTOR' : _WORKERPING,
  '__module__' : 'population_server_pb2'
  # @@protoc_insertion_point(class_scope:WorkerPing)
  })
_sym_db.RegisterMessage(WorkerPing)

PayoffTableKey = _reflection.GeneratedProtocolMessageType('PayoffTableKey', (_message.Message,), {
  'DESCRIPTOR' : _PAYOFFTABLEKEY,
  '__module__' : 'population_server_pb2'
  # @@protoc_insertion_point(class_scope:PayoffTableKey)
  })
_sym_db.RegisterMessage(PayoffTableKey)

PolicyInfo = _reflection.GeneratedProtocolMessageType('PolicyInfo', (_message.Message,), {
  'DESCRIPTOR' : _POLICYINFO,
  '__module__' : 'population_server_pb2'
  # @@protoc_insertion_point(class_scope:PolicyInfo)
  })
_sym_db.RegisterMessage(PolicyInfo)

Confirmation = _reflection.GeneratedProtocolMessageType('Confirmation', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMATION,
  '__module__' : 'population_server_pb2'
  # @@protoc_insertion_point(class_scope:Confirmation)
  })
_sym_db.RegisterMessage(Confirmation)

EvalMatchupOrder = _reflection.GeneratedProtocolMessageType('EvalMatchupOrder', (_message.Message,), {
  'DESCRIPTOR' : _EVALMATCHUPORDER,
  '__module__' : 'population_server_pb2'
  # @@protoc_insertion_point(class_scope:EvalMatchupOrder)
  })
_sym_db.RegisterMessage(EvalMatchupOrder)

EvalMatchupResult = _reflection.GeneratedProtocolMessageType('EvalMatchupResult', (_message.Message,), {
  'DESCRIPTOR' : _EVALMATCHUPRESULT,
  '__module__' : 'population_server_pb2'
  # @@protoc_insertion_point(class_scope:EvalMatchupResult)
  })
_sym_db.RegisterMessage(EvalMatchupResult)

ManagerStats = _reflection.GeneratedProtocolMessageType('ManagerStats', (_message.Message,), {
  'DESCRIPTOR' : _MANAGERSTATS,
  '__module__' : 'population_server_pb2'
  # @@protoc_insertion_point(class_scope:ManagerStats)
  })
_sym_db.RegisterMessage(ManagerStats)

EvalResultRequest = _reflection.GeneratedProtocolMessageType('EvalResultRequest', (_message.Message,), {
  'DESCRIPTOR' : _EVALRESULTREQUEST,
  '__module__' : 'population_server_pb2'
  # @@protoc_insertion_point(class_scope:EvalResultRequest)
  })
_sym_db.RegisterMessage(EvalResultRequest)



_POPULATIONSERVER = _descriptor.ServiceDescriptor(
  name='PopulationServer',
  full_name='PopulationServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=735,
  serialized_end=1177,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='PopulationServer.Ping',
    index=0,
    containing_service=None,
    input_type=_WORKERPING,
    output_type=_CONFIRMATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetManagerStats',
    full_name='PopulationServer.GetManagerStats',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_MANAGERSTATS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLatestPayoffTableKey',
    full_name='PopulationServer.GetLatestPayoffTableKey',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_PAYOFFTABLEKEY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitNewPolicyForPopulation',
    full_name='PopulationServer.SubmitNewPolicyForPopulation',
    index=3,
    containing_service=None,
    input_type=_POLICYINFO,
    output_type=_CONFIRMATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RequestEvalMatchup',
    full_name='PopulationServer.RequestEvalMatchup',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_EVALMATCHUPORDER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitEvalMatchupResult',
    full_name='PopulationServer.SubmitEvalMatchupResult',
    index=5,
    containing_service=None,
    input_type=_EVALMATCHUPRESULT,
    output_type=_CONFIRMATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RequestEvalResult',
    full_name='PopulationServer.RequestEvalResult',
    index=6,
    containing_service=None,
    input_type=_EVALRESULTREQUEST,
    output_type=_EVALMATCHUPRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POPULATIONSERVER)

DESCRIPTOR.services_by_name['PopulationServer'] = _POPULATIONSERVER

# @@protoc_insertion_point(module_scope)
